
name: Hi Prashant
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo "Hi!"
      - name: Print working directory
        run: pwd
      - name: List directory contents
        run: ls -la
      - name: Check IP address of server
        run: hostname -I
